### ISSUE TITLE
ld: cannot find -lCommon (ubuntu 16.04)

### ISSUE THREAD

**Issue by rodriguezsergio** [cryptonotefoundation/cryptonote#135]
For some reason I'm having issues compiling. I installed `libcommoncpp2-dev`and tried again, but got the same error. I also made the 1 line change to `src/CMakeLists.txt` where `Common` was moved to before `System` as instructed in https://github.com/cryptonotefoundation/cryptonote/issues/92, but still the issue persists.

What package(s) am I missing?

**Comment by SoraKohaku** [comment]
apt install build-essential libqt4-dev qt5-qmake cmake qttools5-dev
libqt5webkit5-dev qttools5-dev-tools qt5-default python-sphinx
texlive-latex-base inotify-tools openssl libssl-dev libdb++-dev
libminiupnpc-dev git sqlite3 libsqlite3-dev g++ libpng-dev gedit python gcc
make libbz2-dev libdb-dev libssl-dev libreadline-dev autoconf libtool
libleveldb-dev libblkid-dev e2fslibs-dev libboost-all-dev libaudit-dev
automake nano qtbase5-dev qt4-dev-tools libqt4-core libqt4-gui libqt5-core
libqt5-gui

**Comment by rainmanp7** [comment]
You don't have to install all that crap lol.
But you could just install the library file you need.

Please mention the gcc version and cmake your using please.

sudo apt-get buildesentials
Could be the trick you need.

build-essentials. I do see gcc, make, and autoconf but most users only know to install build-essentials to get the full gnu/gcc stack.

Your base problem is called.. not the problem. It called a false positive problem.
The real fix for this has been completed.
I have already fixed this ,but it's not for the faint of heart programmer.
 Plus I forget where I put the fix..

But common errors always come back to thins not being updated. Because the system might be updated ,but nit the compiler. Upgraded components underneath cause ,very very strange issues.

Thank you.

**Comment by SoraKohaku** [comment]
this because for who wanna used peer lib. but basically just
build-essential is ok

#closed
