### ISSUE TITLE
Build issue

### ISSUE THREAD

**Issue by sharjeelm** [cryptonotefoundation/cryptonote#144]
mkdir -p build/release
cd build/release && cmake -D CMAKE_BUILD_TYPE=Release ../..
/bin/sh: 1: cmake: not found
Makefile:16: recipe for target 'cmake-release' failed
make: *** [cmake-release] Error 127

**Comment by SoraKohaku** [comment]
apt install build-essential libqt4-dev qt5-qmake cmake qttools5-dev
libqt5webkit5-dev qttools5-dev-tools qt5-default python-sphinx
texlive-latex-base inotify-tools openssl libssl-dev libdb++-dev
libminiupnpc-dev git sqlite3 libsqlite3-dev g++ libpng-dev gedit python gcc
make libbz2-dev libdb-dev libssl-dev libreadline-dev autoconf libtool
libleveldb-dev libblkid-dev e2fslibs-dev libboost-all-dev libaudit-dev
automake nano qtbase5-dev qt4-dev-tools libqt4-core libqt4-gui libqt5-core
libqt5-gui

On Jan 15, 2018 7:24 PM, "sharjeelm" <notifications@github.com> wrote:

mkdir -p build/release
cd build/release && cmake -D CMAKE_BUILD_TYPE=Release ../..
/bin/sh: 1: cmake: not found
Makefile:16: recipe for target 'cmake-release' failed
make: *** [cmake-release] Error 127

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/cryptonotefoundation/cryptonote/issues/144>, or mute
the thread

**Comment by sharjeelm** [comment]
Thanks for your help

**Comment by SoraKohaku** [comment]
no prob
