### ISSUE TITLE
ERROR [Miner] Error occured during mining: Enable multithreading to use std::thread: Operation not permitted

### ISSUE THREAD

**Issue by jared201** [cryptonotefoundation/cryptonote#152]
Googling for this one again, but can't find any convincing solutions. Anyone got the same problem? I'm running the coin daemon on Ubuntu 14.04

**Comment by rainmanp7** [comment]
That's a specific minersgate issue.
Your mining on miners gate.. but asking cryptonote to solve a mining event for a specific coin? Best bet? Go to the coin or contact Minersgate directly in the minersgate chat. That chat is directly in their program.

**Comment by SoraKohaku** [comment]
it's fixed on my repo #close

**Comment by rainmanp7** [comment]
std::thread would be calling a boost thread right ;-)
Or c++ library :-)

Multithreading can have the actual fix posted right here instead of hunting repos

**Comment by SoraKohaku** [comment]
right. i think files here completed. but not upgrade...

On Feb 1, 2018 2:37 PM, "PHFirecoin" <notifications@github.com> wrote:

std::thread would be calling a boost thread right ;-)
Or c++ library :-)

Multithreading can have the actual fix posted right here instead of hunting
repos

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/cryptonotefoundation/cryptonote/issues/152#issuecomment-362164054>,
or mute the thread

**Comment by jared201** [comment]
@rainmanp7  thanks! this issue has been resolved 2 weeks ago

**Comment by pocketchange8** [comment]
I've been struggling on this issue for two weeks now.   Ubuntu 14.4, and using the exact supporting installs direct from Cryptonote.   Their just isn't any information on the net with this problem.    I've installed 14.4 on 5 different systems and they all have this same issue.   Please help.

**Comment by rainmanp7** [comment]
Are you using a virtual machine and have multhreading or special cpu
features enabled ?
Am just curious, trying to help.

**Comment by SoraKohaku** [comment]
make sure all base installed. hmmm this old very problem. you can see my
work. that compatible ubuntu new and old.
