### ISSUE TITLE
what's the difference between the ./miner and start_mining?

### ISSUE THREAD

**Issue by jared201** [cryptonotefoundation/cryptonote#153]
I'm not sure which one really works, ./miner <address> or start_mining <address> 

not getting anything mined

**Comment by SoraKohaku** [comment]
see if ram full or process used

**Comment by jared201** [comment]
total       used       free     shared    buffers     cached
Mem:      12293456    3642956    8650500         44     262508    2574264
-/+ buffers/cache:     806184   11487272
Swap:     12571644      21360   12550284

looks ok

**Comment by SoraKohaku** [comment]
try mine

On Jan 21, 2018 12:08 PM, "Jared Odulio" <notifications@github.com> wrote:

         total       used       free     shared    buffers     cached

Mem: 12293456 3642956 8650500 44 262508 2574264
-/+ buffers/cache: 806184 11487272
Swap: 12571644 21360 12550284

looks ok

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/cryptonotefoundation/cryptonote/issues/153#issuecomment-359220346>,
or mute the thread

**Comment by jared201** [comment]
this is resolved now
